# Generated by Django 5.1 on 2025-01-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
