# Generated by Django 5.1 on 2025-01-02 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_cuisinetype_remove_restaurant_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
