# Generated by Django 5.1 on 2025-01-03 15:06

import django.db.models.deletion
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_cuisinetype_remove_restaurant_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chainrestaurant',
            name='menu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='cuisine_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurants.cuisinetype'),
        ),